theme: jekyll-theme-cayman
title: Filippo Antonazzo
description: Ph.D. student at Univeristy of Lille
link1url: index
link1tag: Home
link2url: publications
link2tag: Publications
link3url: apps
link3tag: Apps
link4url: links
link4tag: Links
header:
  image: assets/css/ind.jpeg
