theme: jekyll-theme-cayman
title: La Brace Accesa
description: Salciccia piccante, quella dolce, provolone ,le olive...
link2url: publications
link2tag: Publications
header:
  image: assets/css/ind.jpeg
